
####################  log配置  ########################
logging:
  config: classpath:logback-boot.xml

####################  Tomcat配置  ######################
server:
  port: 8081 #端口号
  tomcat:
    max-threads: 1000 #最大线程数

####################  mybatis配置  ######################
mybatis:
  mapperLocations: classpath:mappers/**/*.xml #扫描文件夹下的xml

slaveMappers:
  mapperLocations: classpath:mappers/salve-mappers/**/*.xml #从库的扫描路径(自定义的)

####################  数据库  ############################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cysharedata?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  thymeleaf:
      cache: false
      encoding: UTF-8
  #    content-type: text/html
      # 设置LEGACYHTML5 并添加依赖 可以使thymeleaf不严格模式
      mode: LEGACYHTML5
  #    mode: LEGACYHTML5
      suffix: .html
      prefix: classpath:/templates/

#自定义的
jdbc:
  datasource:
    dbone:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
    dbtwo:
      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver