
####################  log配置  ########################
logging:
  config: classpath:logback-boot.xml

####################  Tomcat配置  ######################
server:
  port: 8081 #端口号
  tomcat:
    max-threads: 1000 #最大线程数

####################  mybatis配置  ######################
mybatis:
  mapperLocations: classpath:mappers/**/*.xml #扫描文件夹下的xml

slaveMappers:
  mapperLocations: classpath:mappers/salve-mappers/**/*.xml #从库的扫描路径(自定义的)

####################  数据库  ############################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechatstore?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

#自定义的
jdbc:
  datasource:
    dbone:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
    dbtwo:
      url: jdbc:mysql://localhost:3306/test1?characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver